### Criar uma empresa
POST http://localhost:3001/v1/companies
Content-Type: application/json

{
  "name": "adidas",
  "cnpj": "59546515000133",
  "responsibleId": 1
 }

###
GET http://localhost:3001/v1/companies

###
GET http://localhost:3001/v1/companies/11

###
GET http://localhost:3001/v1/companies/search/nike

###
GET http://localhost:3001/v1/companies/11/products

###
GET http://localhost:3001/v1/companies/2/products?name=air%20force%20max

###
PATCH http://localhost:3001/v1/companies/11
Content-Type: application/json

{
  "name": "umbro"
}

###
DELETE http://localhost:3001/v1/companies/13

###
POST http://localhost:3001/v1/products
Content-Type: application/json

{
  "name": "adidas",
  "price": 250.99,
  "description": "Adidas 2",
  "companyId": 15
}

###
GET http://localhost:3001/v1/products

###
GET http://localhost:3001/v1/products/3

###
PATCH http://localhost:3001/v1/products/3
Content-Type: application/json

{
  "name": "air max"
}

###
DELETE http://localhost:3001/v1/products/6

